import type { ComponentType } from "react";

export type MdxModule = {
  default: ComponentType;
  metadata: { title: string; description: string; category: string; date: string };
};

export const mdxLoaders = {
  "de/codes/card-chronicles-codes": () => import("../../content/de/codes/card-chronicles-codes.mdx") as Promise<MdxModule>,
  "de/guide/card-chronicles-beginner-guide": () => import("../../content/de/guide/card-chronicles-beginner-guide.mdx") as Promise<MdxModule>,
  "de/guide/card-chronicles-guide": () => import("../../content/de/guide/card-chronicles-guide.mdx") as Promise<MdxModule>,
  "de/guide/card-chronicles-roblox-guide": () => import("../../content/de/guide/card-chronicles-roblox-guide.mdx") as Promise<MdxModule>,
  "de/guide/card-chronicles-tips": () => import("../../content/de/guide/card-chronicles-tips.mdx") as Promise<MdxModule>,
  "de/lineup/card-chronicles-best-lineup": () => import("../../content/de/lineup/card-chronicles-best-lineup.mdx") as Promise<MdxModule>,
  "de/lineup/card-chronicles-card-team": () => import("../../content/de/lineup/card-chronicles-card-team.mdx") as Promise<MdxModule>,
  "de/ranks/card-chronicles-rank-guide": () => import("../../content/de/ranks/card-chronicles-rank-guide.mdx") as Promise<MdxModule>,
  "de/ranks/card-chronicles-ranks": () => import("../../content/de/ranks/card-chronicles-ranks.mdx") as Promise<MdxModule>,
  "de/system/card-chronicles-private-server": () => import("../../content/de/system/card-chronicles-private-server.mdx") as Promise<MdxModule>,
  "de/system/card-chronicles-roblox": () => import("../../content/de/system/card-chronicles-roblox.mdx") as Promise<MdxModule>,
  "en/codes/card-chronicles-codes": () => import("../../content/en/codes/card-chronicles-codes.mdx") as Promise<MdxModule>,
  "en/guide/card-chronicles-beginner-guide": () => import("../../content/en/guide/card-chronicles-beginner-guide.mdx") as Promise<MdxModule>,
  "en/guide/card-chronicles-guide": () => import("../../content/en/guide/card-chronicles-guide.mdx") as Promise<MdxModule>,
  "en/guide/card-chronicles-roblox-guide": () => import("../../content/en/guide/card-chronicles-roblox-guide.mdx") as Promise<MdxModule>,
  "en/guide/card-chronicles-tips": () => import("../../content/en/guide/card-chronicles-tips.mdx") as Promise<MdxModule>,
  "en/lineup/card-chronicles-best-lineup": () => import("../../content/en/lineup/card-chronicles-best-lineup.mdx") as Promise<MdxModule>,
  "en/lineup/card-chronicles-card-team": () => import("../../content/en/lineup/card-chronicles-card-team.mdx") as Promise<MdxModule>,
  "en/ranks/card-chronicles-rank-guide": () => import("../../content/en/ranks/card-chronicles-rank-guide.mdx") as Promise<MdxModule>,
  "en/ranks/card-chronicles-ranks": () => import("../../content/en/ranks/card-chronicles-ranks.mdx") as Promise<MdxModule>,
  "en/system/card-chronicles-private-server": () => import("../../content/en/system/card-chronicles-private-server.mdx") as Promise<MdxModule>,
  "en/system/card-chronicles-roblox": () => import("../../content/en/system/card-chronicles-roblox.mdx") as Promise<MdxModule>,
  "es/codes/card-chronicles-codes": () => import("../../content/es/codes/card-chronicles-codes.mdx") as Promise<MdxModule>,
  "es/guide/card-chronicles-beginner-guide": () => import("../../content/es/guide/card-chronicles-beginner-guide.mdx") as Promise<MdxModule>,
  "es/guide/card-chronicles-guide": () => import("../../content/es/guide/card-chronicles-guide.mdx") as Promise<MdxModule>,
  "es/guide/card-chronicles-roblox-guide": () => import("../../content/es/guide/card-chronicles-roblox-guide.mdx") as Promise<MdxModule>,
  "es/guide/card-chronicles-tips": () => import("../../content/es/guide/card-chronicles-tips.mdx") as Promise<MdxModule>,
  "es/lineup/card-chronicles-best-lineup": () => import("../../content/es/lineup/card-chronicles-best-lineup.mdx") as Promise<MdxModule>,
  "es/lineup/card-chronicles-card-team": () => import("../../content/es/lineup/card-chronicles-card-team.mdx") as Promise<MdxModule>,
  "es/ranks/card-chronicles-rank-guide": () => import("../../content/es/ranks/card-chronicles-rank-guide.mdx") as Promise<MdxModule>,
  "es/ranks/card-chronicles-ranks": () => import("../../content/es/ranks/card-chronicles-ranks.mdx") as Promise<MdxModule>,
  "es/system/card-chronicles-private-server": () => import("../../content/es/system/card-chronicles-private-server.mdx") as Promise<MdxModule>,
  "es/system/card-chronicles-roblox": () => import("../../content/es/system/card-chronicles-roblox.mdx") as Promise<MdxModule>,
  "pt/codes/card-chronicles-codes": () => import("../../content/pt/codes/card-chronicles-codes.mdx") as Promise<MdxModule>,
  "pt/guide/card-chronicles-beginner-guide": () => import("../../content/pt/guide/card-chronicles-beginner-guide.mdx") as Promise<MdxModule>,
  "pt/guide/card-chronicles-guide": () => import("../../content/pt/guide/card-chronicles-guide.mdx") as Promise<MdxModule>,
  "pt/guide/card-chronicles-roblox-guide": () => import("../../content/pt/guide/card-chronicles-roblox-guide.mdx") as Promise<MdxModule>,
  "pt/guide/card-chronicles-tips": () => import("../../content/pt/guide/card-chronicles-tips.mdx") as Promise<MdxModule>,
  "pt/lineup/card-chronicles-best-lineup": () => import("../../content/pt/lineup/card-chronicles-best-lineup.mdx") as Promise<MdxModule>,
  "pt/lineup/card-chronicles-card-team": () => import("../../content/pt/lineup/card-chronicles-card-team.mdx") as Promise<MdxModule>,
  "pt/ranks/card-chronicles-rank-guide": () => import("../../content/pt/ranks/card-chronicles-rank-guide.mdx") as Promise<MdxModule>,
  "pt/ranks/card-chronicles-ranks": () => import("../../content/pt/ranks/card-chronicles-ranks.mdx") as Promise<MdxModule>,
  "pt/system/card-chronicles-private-server": () => import("../../content/pt/system/card-chronicles-private-server.mdx") as Promise<MdxModule>,
  "pt/system/card-chronicles-roblox": () => import("../../content/pt/system/card-chronicles-roblox.mdx") as Promise<MdxModule>,
} as const;
